quarkus.http.auth.basic=true
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.admin=admin
quarkus.security.users.embedded.roles.admin=admin
quarkus.jacoco.enabled=true
quarkus.jacoco.report=true
quarkus.package.write-transformed-bytecode-to-build-output=true
